name: artbooking
description: Your inspirational space.
licence: MPL-2.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.43.0+2

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  adaptive_theme: 2.3.0
  algolia: 1.0.4
  animations: 2.0.2
  beamer: 1.2.0
  cloud_firestore: 3.1.6
  cloud_functions: 3.2.5
  cross_local_storage: 2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.4
  easy_localization: 3.0.0
  expansion_tile_card: 2.0.0
  extended_image: 6.0.1
  file_picker: 4.3.1
  file_picker_cross: 4.5.0
  firebase_analytics: 9.0.5
  firebase_auth: 3.3.5
  firebase_core: 1.11.0
  firebase_storage: 10.2.5
  flash: 2.0.3+2
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.3
  font_awesome_flutter: 9.2.0
  global_configuration: 2.0.0-nullsafety.0
  google_fonts: 2.2.0
  image: 3.1.0
  image_editor: 1.0.2
  logger: 1.1.0
  introduction_screen: 2.1.0
  jiffy: 5.0.0
  mime_type: 1.0.0
  modal_bottom_sheet: 2.0.0
  photo_view: 0.13.0
  share: 2.0.4
  shimmer_animation: 2.1.0+1
  simple_animations: 4.0.1
  sticky_headers: 0.2.0
  supercharged: 2.1.1
  timelines: 0.1.0
  unicons: 2.0.2
  url_launcher: 6.0.17
  url_strategy: 0.2.0
  verbal_expressions: 1.0.0
  waterfall_flow: 3.0.2

dev_dependencies:
  build_runner:
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/app_icon/32.png
    - assets/images/app_icon/64.png
    - assets/images/app_icon/96.png
    - assets/images/app_icon/128.png
    - assets/images/app_icon/512.png
    - assets/images/app_icon/1080.png
    - assets/images/app_icon/animation.gif
    - assets/images/default-avatar.png
    - assets/images/gummy-canvas.png
    - assets/translations/
    - assets/cfg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
