enum EnumSectionAction {
  changeDataMode,
  delete,
  editBackgroundColor,
  editTextColor,
  expand,
  moveDown,
  moveUp,
  rename,
  renameTitle,
  selectBooks,
  selectIllustrations,
  setChosenDataMode,
  setSyncDataMode,
  settings,
  shrink,
}
